### ISSUE TITLE
The issue of KeyError: 'video_fnames' during inference

### ISSUE THREAD

**Issue by tuyunbin** [j-min/HiREST#6]
Hi, Dr. Cho, there is an error when I run bash scripts/run.sh for inference. When implementing Moment_segmentation Prediction, I met an error of KeyError: 'video_fnames'. It seems that the list of 'video_fnames' is empty.
![image](https://github.com/j-min/HiREST/assets/22414019/a0c16995-f752-4cd8-a5e7-f893a3c10f45)

**Comment by aszala** [comment]
Thanks for pointing this out!

It occurs when you try to skip the first stage of moment retrieval.
I've just pushed an update that should resolve this error.

Please let me know if the issue continues.

**Comment by tuyunbin** [comment]
The error still exists. I may find the reason: the ``steps'' in the file \data\splits\all_data_test.json are empty. In this case, when implementing these lines:                         
if len(video_ann['steps']) == 0:
                            continue, 
 the model will not implement the remaining parts of for loop. Thus, the test_moment_segmentation_loader and test_step_captioning_loader are empty. The above issue will appear. The solution is to run the other two files:
bash scripts/run_val.sh
bash scripts/score_val.sh
